version: "3.7"
services:
  postgres_db:
    image: postgres:16
    container_name: db_app
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
  app:
    container_name: fastapi_app
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5555:4127"
    depends_on:
      - postgres_db
