"""fix nullables and rename column

Revision ID: 795f155e89d8
Revises: 33bc963b3625
Create Date: 2023-12-18 23:49:08.971384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '795f155e89d8'
down_revision: Union[str, None] = '33bc963b3625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('published_at', sa.Date(), nullable=True))
    op.drop_column('album', 'created_at')
    op.alter_column('band', 'created_at',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('band', 'created_at',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('album', sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('album', 'published_at')
    # ### end Alembic commands ###
